all:
	gcc main.c curve25519_base_256_17.c ../../base_256_17/256arithmetic/bignum.c ../../_common_libs/radix17.c ../../_common_libs/radix17_curveParams.c ../../_common_libs/common.c -o out
clean:
	rm out